FROM neo4j:4.4-enterprise

COPY init-db/neo4j-db/apoc.jar /var/lib/neo4j/plugins/
COPY init-db/neo4j-db/agora-project.cypher /var/lib/neo4j/import/
COPY init-db/neo4j-db/initialize-db.cypher /var/lib/neo4j/import/